-- Generated by clrsync

return {
    bg        = "{background.hex}",
    surface   = "{surface.hex}",
    surface2  = "{surface_variant.hex}",
    surface3  = "{surface_container.hex}",
    surface4  = "{surface_high.hex}",

    fg        = "{foreground.hex}",
    muted     = "{editor_comment.hex}",

    accent    = "{accent.hex}",
    accent2   = "{accent_secondary.hex}",
    border    = "{border.hex}",
    border_focused = "{border_focused.hex}",

    error     = "{error.hex}",
    warning   = "{warning.hex}",
    success   = "{success.hex}",
    info      = "{info.hex}",

    on_accent = "{background.hex}",
    on_error  = "{on_error.hex}",
}
