-- Generated by clrsync

return {
    bg        = "#0A1318",
    surface   = "#162025",
    surface2  = "#232D33",
    surface3  = "#313B41",
    surface4  = "#3F4A50",

    fg        = "#C1C4C5",
    muted     = "#5D696F",

    accent    = "#C1C4C5",
    accent2   = "#A5C5F8",
    border    = "#465158",
    border_focused = "#556167",

    error     = "#FEAB9E",
    warning   = "#EDB87A",
    success   = "#9BD59C",
    info      = "#A5C5F8",

    on_accent = "#0A1318",
    on_error  = "#111111",
}
