[colors]
accent = '#95A328FF'
accent_secondary = '#95A328FF'
background = '#151515FF'
base00 = '#151515FF'
base01 = '#1C1C1CFF'
base02 = '#292929FF'
base03 = '#7A7A7AFF'
base04 = '#B1B19FFF'
base05 = '#C2C2B0FF'
base06 = '#D4D4C1FF'
base07 = '#E6E6D3FF'
base08 = '#B44242FF'
base09 = '#DC7671FF'
base0A = '#E1C135FF'
base0B = '#95A328FF'
base0C = '#A48B4AFF'
base0D = '#60928FFF'
base0E = '#7C435AFF'
base0F = '#A35E5AFF'
border = '#3F3639FF'
border_focused = '#E1C135FF'
cursor = '#E1C135FF'
editor_active_line_border = '#3F3639FF'
editor_attribute = '#E1C135FF'
editor_background = '#151515FF'
editor_boolean = '#DC7671FF'
editor_bracket_match = '#E1C135FF'
editor_class = '#60928FFF'
editor_comment = '#7A7A7AFF'
editor_constant = '#DC7671FF'
editor_cursor = '#E1C135FF'
editor_decorator = '#E1C135FF'
editor_deleted = '#B44242FF'
editor_enum = '#60928FFF'
editor_error = '#B44242FF'
editor_error_background = '#2A1515FF'
editor_escape_character = '#DC7671FF'
editor_find_range_highlight = '#E1C135FF'
editor_folded_background = '#1C1C1CFF'
editor_foreground = '#C2C2B0FF'
editor_function = '#95A328FF'
editor_gutter_background = '#151515FF'
editor_gutter_foreground = '#7A7A7AFF'
editor_hint = '#95A328FF'
editor_hint_background = '#1A2A15FF'
editor_ignored = '#7A7A7AFF'
editor_indent_guide = '#2A2A2AFF'
editor_indent_guide_active = '#3F3639FF'
editor_info = '#60928FFF'
editor_info_background = '#15252AFF'
editor_inserted = '#95A328FF'
editor_interface = '#60928FFF'
editor_invalid = '#B44242FF'
editor_keyword = '#CEB34FFF'
editor_line_highlight = '#1C1C1CFF'
editor_line_number = '#86596CFF'
editor_line_number_active = '#C2C2B0FF'
editor_link = '#60928FFF'
editor_modified = '#E1C135FF'
editor_namespace = '#86596CFF'
editor_number = '#DC7671FF'
editor_operator = '#C2C2B0FF'
editor_parameter = '#60928FFF'
editor_property = '#76C39BFF'
editor_punctuation = '#B0AFA8FF'
editor_regex = '#CEB34FFF'
editor_search_match = '#E1C135FF'
editor_search_match_active = '#E1C135FF'
editor_selection = '#3F3639FF'
editor_selection_inactive = '#2A2A2AFF'
editor_string = '#76C39BFF'
editor_tag = '#B44242FF'
editor_type = '#60928FFF'
editor_variable = '#C2C2B0FF'
editor_warning = '#E1C135FF'
editor_warning_background = '#2A2515FF'
editor_whitespace = '#3F3639FF'
error = '#B44242FF'
foreground = '#C2C2B0FF'
info = '#60928FFF'
on_accent = '#111111FF'
on_accent_secondary = '#111111FF'
on_background = '#C2C2B0FF'
on_error = '#151515FF'
on_info = '#151515FF'
on_success = '#151515FF'
on_surface = '#C2C2B0FF'
on_surface_variant = '#CCCCCCFF'
on_warning = '#151515FF'
success = '#95A328FF'
surface = '#1C1C1CFF'
surface_container = '#373737FF'
surface_high = '#454545FF'
surface_variant = '#292929FF'
term0 = '#151515FF'
term1 = '#B44242FF'
term10 = '#E8E85AFF'
term11 = '#9E9052FF'
term12 = '#76C39BFF'
term13 = '#86596CFF'
term14 = '#CEB34FFF'
term15 = '#B0AFA8FF'
term2 = '#95A328FF'
term3 = '#E1C135FF'
term4 = '#60928FFF'
term5 = '#7C435AFF'
term6 = '#A48B4AFF'
term7 = '#C2C2B0FF'
term8 = '#3F3639FF'
term9 = '#DC7671FF'
warning = '#E1C135FF'

[general]
name = 'cursed'
