[colors]
accent = '#9A8652FF'
accent_secondary = '#3A898CFF'
background = '#111111FF'
base00 = '#111111FF'
base01 = '#1D1D1DFF'
base02 = '#383838FF'
base03 = '#849899FF'
base04 = '#C0C0C0FF'
base05 = '#D2D2D2FF'
base06 = '#E4E4E4FF'
base07 = '#F6F6F6FF'
base08 = '#AA4E4AFF'
base09 = '#B47837FF'
base0A = '#9A8652FF'
base0B = '#668A51FF'
base0C = '#3A898CFF'
base0D = '#5A7CA8FF'
base0E = '#AA477BFF'
base0F = '#8A6A4AFF'
border = '#4D4D4DFF'
border_focused = '#5D5D5DFF'
cursor = '#D2D2D2FF'
editor_active_line_border = '#464646FF'
editor_attribute = '#9A8652FF'
editor_background = '#111111FF'
editor_boolean = '#B47837FF'
editor_bracket_match = '#3A898CFF'
editor_class = '#3A898CFF'
editor_comment = '#849899FF'
editor_constant = '#B47837FF'
editor_cursor = '#D2D2D2FF'
editor_decorator = '#9A8652FF'
editor_deleted = '#AA4E4AFF'
editor_enum = '#3A898CFF'
editor_error = '#AA4E4AFF'
editor_error_background = '#291715FF'
editor_escape_character = '#B47837FF'
editor_find_range_highlight = '#221C0BFF'
editor_folded_background = '#1D1D1DFF'
editor_foreground = '#D2D2D2FF'
editor_function = '#5A7CA8FF'
editor_gutter_background = '#111111FF'
editor_gutter_foreground = '#849899FF'
editor_hint = '#668A51FF'
editor_hint_background = '#162011FF'
editor_ignored = '#849899FF'
editor_indent_guide = '#383838FF'
editor_indent_guide_active = '#464646FF'
editor_info = '#5A7CA8FF'
editor_info_background = '#131D2AFF'
editor_inserted = '#668A51FF'
editor_interface = '#3A898CFF'
editor_invalid = '#AA4E4AFF'
editor_keyword = '#AA477BFF'
editor_line_highlight = '#1D1D1DFF'
editor_line_number = '#849899FF'
editor_line_number_active = '#D2D2D2FF'
editor_link = '#5A7CA8FF'
editor_modified = '#B47837FF'
editor_namespace = '#5A7CA8FF'
editor_number = '#B47837FF'
editor_operator = '#D2D2D2FF'
editor_parameter = '#B5B5B5FF'
editor_property = '#9A8652FF'
editor_punctuation = '#D2D2D2FF'
editor_regex = '#AA477BFF'
editor_search_match = '#221C0BFF'
editor_search_match_active = '#9A8652FF'
editor_selection = '#383838FF'
editor_selection_inactive = '#2A2A2AFF'
editor_string = '#668A51FF'
editor_tag = '#AA4E4AFF'
editor_type = '#3A898CFF'
editor_variable = '#D2D2D2FF'
editor_warning = '#B47837FF'
editor_warning_background = '#26190DFF'
editor_whitespace = '#464646FF'
error = '#AA4E4AFF'
foreground = '#D2D2D2FF'
info = '#5A7CA8FF'
on_accent = '#111111FF'
on_accent_secondary = '#111111FF'
on_background = '#D2D2D2FF'
on_error = '#F4F4F4FF'
on_info = '#111111FF'
on_success = '#111111FF'
on_surface = '#D2D2D2FF'
on_surface_variant = '#849899FF'
on_warning = '#111111FF'
success = '#668A51FF'
surface = '#1D1D1DFF'
surface_container = '#383838FF'
surface_high = '#464646FF'
surface_variant = '#2A2A2AFF'
term0 = '#111111FF'
term1 = '#AA4E4AFF'
term10 = '#83A96EFF'
term11 = '#B9A570FF'
term12 = '#779AC8FF'
term13 = '#CC6599FF'
term14 = '#5AA8ABFF'
term15 = '#F6F6F6FF'
term2 = '#668A51FF'
term3 = '#9A8652FF'
term4 = '#5A7CA8FF'
term5 = '#AA477BFF'
term6 = '#3A898CFF'
term7 = '#B5B5B5FF'
term8 = '#555555FF'
term9 = '#CC6C66FF'
warning = '#B47837FF'

[general]
name = 'dark'
