[colors]
accent = '#4B614BFF'
accent_secondary = '#4B614BFF'
background = '#040409FF'
base00 = '#040409FF'
base01 = '#0D0E15FF'
base02 = '#262730FF'
base03 = '#595B64FF'
base04 = '#EDEDEDFF'
base05 = '#FFFFFFFF'
base06 = '#FFFFFFFF'
base07 = '#FFFFFFFF'
base08 = '#854B43FF'
base09 = '#A5685FFF'
base0A = '#5A715AFF'
base0B = '#4B614BFF'
base0C = '#8AA68CFF'
base0D = '#355E86FF'
base0E = '#774D74FF'
base0F = '#778F77FF'
border = '#3B3C45FF'
border_focused = '#4A4B54FF'
cursor = '#FFFFFFFF'
editor_active_line_border = '#34353EFF'
editor_attribute = '#5A715AFF'
editor_background = '#040409FF'
editor_boolean = '#A5685FFF'
editor_bracket_match = '#8AA68CFF'
editor_class = '#8AA68CFF'
editor_comment = '#595B65FF'
editor_constant = '#A5685FFF'
editor_cursor = '#FFFFFFFF'
editor_decorator = '#5A715AFF'
editor_deleted = '#8E463CFF'
editor_enum = '#8AA68CFF'
editor_error = '#8E463CFF'
editor_error_background = '#180806FF'
editor_escape_character = '#A5685FFF'
editor_find_range_highlight = '#051106FF'
editor_folded_background = '#0D0E15FF'
editor_foreground = '#FFFFFFFF'
editor_function = '#355E86FF'
editor_gutter_background = '#040409FF'
editor_gutter_foreground = '#595B65FF'
editor_hint = '#4B614BFF'
editor_hint_background = '#051106FF'
editor_ignored = '#595B65FF'
editor_indent_guide = '#262730FF'
editor_indent_guide_active = '#34353EFF'
editor_info = '#295E91FF'
editor_info_background = '#040E1AFF'
editor_inserted = '#4B614BFF'
editor_interface = '#8AA68CFF'
editor_invalid = '#8E463CFF'
editor_keyword = '#774D74FF'
editor_line_highlight = '#0D0E15FF'
editor_line_number = '#595B65FF'
editor_line_number_active = '#FFFFFFFF'
editor_link = '#355E86FF'
editor_modified = '#805108FF'
editor_namespace = '#355E86FF'
editor_number = '#A5685FFF'
editor_operator = '#FFFFFFFF'
editor_parameter = '#FFFFFFFF'
editor_property = '#5A715AFF'
editor_punctuation = '#FFFFFFFF'
editor_regex = '#774D74FF'
editor_search_match = '#051106FF'
editor_search_match_active = '#4B614BFF'
editor_selection = '#262730FF'
editor_selection_inactive = '#191A22FF'
editor_string = '#4B614BFF'
editor_tag = '#854B43FF'
editor_type = '#8AA68CFF'
editor_variable = '#FFFFFFFF'
editor_warning = '#805108FF'
editor_warning_background = '#160B01FF'
editor_whitespace = '#34353EFF'
error = '#8E463CFF'
foreground = '#FFFFFFFF'
info = '#295E91FF'
on_accent = '#F4F4F4FF'
on_accent_secondary = '#F4F4F4FF'
on_background = '#FFFFFFFF'
on_error = '#F4F4F4FF'
on_info = '#F4F4F4FF'
on_success = '#F4F4F4FF'
on_surface = '#FFFFFFFF'
on_surface_variant = '#FFFFFFFF'
on_warning = '#F4F4F4FF'
success = '#4B614BFF'
surface = '#0D0E15FF'
surface_container = '#262730FF'
surface_high = '#34353EFF'
surface_variant = '#191A22FF'
term0 = '#040409FF'
term1 = '#854B43FF'
term10 = '#677E67FF'
term11 = '#778F77FF'
term12 = '#517BA5FF'
term13 = '#956992FF'
term14 = '#A9C6ABFF'
term15 = '#FFFFFFFF'
term2 = '#4B614BFF'
term3 = '#5A715AFF'
term4 = '#355E86FF'
term5 = '#774D74FF'
term6 = '#8AA68CFF'
term7 = '#FFFFFFFF'
term8 = '#42434DFF'
term9 = '#A5685FFF'
warning = '#805108FF'

[general]
name = 'hellwal'