[colors]
accent = '#7A6836FF'
accent_secondary = '#2A6D70FF'
background = '#F2F2F2FF'
base00 = '#F2F2F2FF'
base01 = '#E0E0E0FF'
base02 = '#BCBCBCFF'
base03 = '#5F6E6FFF'
base04 = '#383838FF'
base05 = '#2A2A2AFF'
base06 = '#1D1D1DFF'
base07 = '#101010FF'
base08 = '#9A3A36FF'
base09 = '#8A5A20FF'
base0A = '#7A6836FF'
base0B = '#4A6B38FF'
base0C = '#2A6D70FF'
base0D = '#3D5E88FF'
base0E = '#8A3560FF'
base0F = '#6A5236FF'
border = '#A2A2A2FF'
border_focused = '#929292FF'
cursor = '#2A2A2AFF'
editor_active_line_border = '#ABABABFF'
editor_attribute = '#7A6836FF'
editor_background = '#F2F2F2FF'
editor_boolean = '#8A5A20FF'
editor_bracket_match = '#2A6D70FF'
editor_class = '#2A6D70FF'
editor_comment = '#5F6E6FFF'
editor_constant = '#8A5A20FF'
editor_cursor = '#2A2A2AFF'
editor_decorator = '#7A6836FF'
editor_deleted = '#9A3A36FF'
editor_enum = '#2A6D70FF'
editor_error = '#9A3A36FF'
editor_error_background = '#F5DBD7FF'
editor_escape_character = '#8A5A20FF'
editor_find_range_highlight = '#E9E1CCFF'
editor_folded_background = '#E0E0E0FF'
editor_foreground = '#2A2A2AFF'
editor_function = '#3D5E88FF'
editor_gutter_background = '#F2F2F2FF'
editor_gutter_foreground = '#5F6E6FFF'
editor_hint = '#4A6B38FF'
editor_hint_background = '#D9E7D3FF'
editor_ignored = '#5F6E6FFF'
editor_indent_guide = '#BCBCBCFF'
editor_indent_guide_active = '#ABABABFF'
editor_info = '#3D5E88FF'
editor_info_background = '#D5E3F6FF'
editor_inserted = '#4A6B38FF'
editor_interface = '#2A6D70FF'
editor_invalid = '#9A3A36FF'
editor_keyword = '#8A3560FF'
editor_line_highlight = '#E0E0E0FF'
editor_line_number = '#5F6E6FFF'
editor_line_number_active = '#2A2A2AFF'
editor_link = '#3D5E88FF'
editor_modified = '#8A5A20FF'
editor_namespace = '#3D5E88FF'
editor_number = '#8A5A20FF'
editor_operator = '#2A2A2AFF'
editor_parameter = '#3D3D3DFF'
editor_property = '#7A6836FF'
editor_punctuation = '#2A2A2AFF'
editor_regex = '#8A3560FF'
editor_search_match = '#E9E1CCFF'
editor_search_match_active = '#7A6836FF'
editor_selection = '#BCBCBCFF'
editor_selection_inactive = '#CECECEFF'
editor_string = '#4A6B38FF'
editor_tag = '#9A3A36FF'
editor_type = '#2A6D70FF'
editor_variable = '#2A2A2AFF'
editor_warning = '#8A5A20FF'
editor_warning_background = '#F0DECDFF'
editor_whitespace = '#ABABABFF'
error = '#9A3A36FF'
foreground = '#2A2A2AFF'
info = '#3D5E88FF'
on_accent = '#F4F4F4FF'
on_accent_secondary = '#F4F4F4FF'
on_background = '#2A2A2AFF'
on_error = '#F4F4F4FF'
on_info = '#F4F4F4FF'
on_success = '#F4F4F4FF'
on_surface = '#2A2A2AFF'
on_surface_variant = '#5F6E6FFF'
on_warning = '#F4F4F4FF'
success = '#4A6B38FF'
surface = '#E0E0E0FF'
surface_container = '#BCBCBCFF'
surface_high = '#ABABABFF'
surface_variant = '#CECECEFF'
term0 = '#F2F2F2FF'
term1 = '#9A3A36FF'
term10 = '#2F4F1CFF'
term11 = '#5D4C18FF'
term12 = '#22426AFF'
term13 = '#6A1645FF'
term14 = '#005154FF'
term15 = '#101010FF'
term2 = '#4A6B38FF'
term3 = '#7A6836FF'
term4 = '#3D5E88FF'
term5 = '#8A3560FF'
term6 = '#2A6D70FF'
term7 = '#3D3D3DFF'
term8 = '#9A9A9AFF'
term9 = '#791A1BFF'
warning = '#8A5A20FF'

[general]
name = 'light'
