[colors]
accent = '#C1C4C5FF'
accent_secondary = '#A5C5F8FF'
background = '#0A1318FF'
base00 = '#0A1318FF'
base01 = '#162025FF'
base02 = '#313B41FF'
base03 = '#576369FF'
base04 = '#B0B3B4FF'
base05 = '#C1C4C5FF'
base06 = '#D3D6D7FF'
base07 = '#E5E8E9FF'
base08 = '#F3B0A6FF'
base09 = '#FFD0C6FF'
base0A = '#CFC589FF'
base0B = '#A4D2A4FF'
base0C = '#83D4D3FF'
base0D = '#A5C5F8FF'
base0E = '#E2B1DCFF'
base0F = '#F0E6A8FF'
border = '#465158FF'
border_focused = '#556167FF'
cursor = '#C1C4C5FF'
editor_active_line_border = '#3F4A50FF'
editor_attribute = '#CFC589FF'
editor_background = '#0A1318FF'
editor_boolean = '#FFD0C6FF'
editor_bracket_match = '#83D4D3FF'
editor_class = '#83D4D3FF'
editor_comment = '#5D696FFF'
editor_constant = '#FFD0C6FF'
editor_cursor = '#C1C4C5FF'
editor_decorator = '#CFC589FF'
editor_deleted = '#FEAB9EFF'
editor_enum = '#83D4D3FF'
editor_error = '#FEAB9EFF'
editor_error_background = '#2A1815FF'
editor_escape_character = '#FFD0C6FF'
editor_find_range_highlight = '#0B2027FF'
editor_folded_background = '#162025FF'
editor_foreground = '#C1C4C5FF'
editor_function = '#A5C5F8FF'
editor_gutter_background = '#0A1318FF'
editor_gutter_foreground = '#5D696FFF'
editor_hint = '#9BD59CFF'
editor_hint_background = '#142114FF'
editor_ignored = '#5D696FFF'
editor_indent_guide = '#313B41FF'
editor_indent_guide_active = '#3F4A50FF'
editor_info = '#A5C5F8FF'
editor_info_background = '#151D2BFF'
editor_inserted = '#9BD59CFF'
editor_interface = '#83D4D3FF'
editor_invalid = '#FEAB9EFF'
editor_keyword = '#E2B1DCFF'
editor_line_highlight = '#162025FF'
editor_line_number = '#5D696FFF'
editor_line_number_active = '#C1C4C5FF'
editor_link = '#A5C5F8FF'
editor_modified = '#EDB87AFF'
editor_namespace = '#A5C5F8FF'
editor_number = '#FFD0C6FF'
editor_operator = '#C1C4C5FF'
editor_parameter = '#C1C4C5FF'
editor_property = '#CFC589FF'
editor_punctuation = '#C1C4C5FF'
editor_regex = '#E2B1DCFF'
editor_search_match = '#0B2027FF'
editor_search_match_active = '#C1C4C5FF'
editor_selection = '#313B41FF'
editor_selection_inactive = '#232D33FF'
editor_string = '#A4D2A4FF'
editor_tag = '#F3B0A6FF'
editor_type = '#83D4D3FF'
editor_variable = '#C1C4C5FF'
editor_warning = '#EDB87AFF'
editor_warning_background = '#261A0DFF'
editor_whitespace = '#3F4A50FF'
error = '#FEAB9EFF'
foreground = '#C1C4C5FF'
info = '#A5C5F8FF'
on_accent = '#111111FF'
on_accent_secondary = '#111111FF'
on_background = '#C1C4C5FF'
on_error = '#111111FF'
on_info = '#111111FF'
on_success = '#111111FF'
on_surface = '#C1C4C5FF'
on_surface_variant = '#C1C4C5FF'
on_warning = '#111111FF'
success = '#9BD59CFF'
surface = '#162025FF'
surface_container = '#313B41FF'
surface_high = '#3F4A50FF'
surface_variant = '#232D33FF'
term0 = '#0A1318FF'
term1 = '#F3B0A6FF'
term10 = '#C4F3C4FF'
term11 = '#F0E6A8FF'
term12 = '#C5E6FFFF'
term13 = '#FFD1FDFF'
term14 = '#A3F5F4FF'
term15 = '#C1C4C5FF'
term2 = '#A4D2A4FF'
term3 = '#CFC589FF'
term4 = '#A5C5F8FF'
term5 = '#E2B1DCFF'
term6 = '#83D4D3FF'
term7 = '#C1C4C5FF'
term8 = '#4E595FFF'
term9 = '#FFD0C6FF'
warning = '#EDB87AFF'

[general]
name = 'pywal16'