-- Hyprland Monitor Configuration
-- Generated by basedgoose.shell Display Manager
-- https://wiki.hypr.land/Configuring/Basics/Monitors/

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@100.00",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-2",
    mode     = "3840x2160@60",
    position = "1920x0",
    scale    = 1,
    mirror   = "HDMI-A-1",
})
