# Input
# Devices: swaymsg -t get_inputs

input type:keyboard {
    xkb_layout us,ru
    xkb_options grp:alt_shift_toggle
    xkb_numlock enabled
    repeat_delay 250
    repeat_rate 35
}

input type:touchpad {
    natural_scroll enabled
    dwt enabled
    tap enabled
    click_method clickfinger
    scroll_factor 0.5
}

focus_follows_mouse yes
mouse_warping output
focus_on_window_activation focus
