font pango:$font

gaps inner 0
gaps outer 0
smart_gaps off

default_border pixel 1
default_floating_border pixel 1
hide_edge_borders smart
titlebar_padding 1

# class                 border   background  text    indicator  child_border
client.focused          $accent  $surface    $fg     $accent    $accent
client.focused_inactive $border  $bg         $muted  $border    $border
client.unfocused        $border  $bg         $muted  $border    $border
client.urgent           $error   $error      $bg     $error     $error
client.background       $bg

bar {
    swaybar_command waybar
}
