# Window rules

### Generic dialogs
for_window [window_role="pop-up|bubble|dialog|menu|task_dialog"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable
for_window [window_type="splash"] floating enable

for_window [title="^(Open File|Open Folder|Save As|Select a File|Choose wallpaper|Library|File Upload)"] floating enable, move position center
for_window [title="(wants to save|wants to open)$"] floating enable, move position center
for_window [title="Welcome$"] floating enable

### Floating utilities
for_window [app_id="^(pavucontrol|org\\.pulseaudio\\.pavucontrol)$"] floating enable, resize set 45ppt 45ppt, move position center
for_window [app_id="^nm-connection-editor$"] floating enable, resize set 45ppt 45ppt, move position center
for_window [app_id="^blueberry\\.py$"] floating enable
for_window [app_id="^guifetch$"] floating enable
for_window [app_id="^kcm_.*"] floating enable
for_window [app_id=".*bluedevilwizard$"] floating enable
for_window [app_id="^org\\.freedesktop\\.impl\\.portal\\.desktop\\.kde$"] floating enable
for_window [class="^Zotero$"] floating enable, resize set 45ppt 45ppt, move position center

### Screenshot overlay
for_window [app_id="^flameshot$"] floating enable, border none, fullscreen disable, move absolute position 0 0
for_window [class="^flameshot$"] floating enable, border none, fullscreen disable, move absolute position 0 0

### Picture-in-Picture
for_window [title="^[Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture"] floating enable, sticky enable, resize set 25ppt 25ppt, move position 73ppt 72ppt

### Dolphin's copy dialog insists on being in the way
for_window [title="^Copying — Dolphin$"] floating enable, move position 40 80

for_window [class="^steam_app.*"] inhibit_idle fullscreen
