# Autostart

exec dbus-update-activation-environment --systemd --all
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP

exec /usr/bin/gnome-keyring-daemon --start "--components=pkcs11,secrets,ssh,gpg"
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec dunst
exec udiskie
exec nm-applet -i
exec kdeconnectd
exec flameshot
exec bitwarden-desktop

exec wl-paste --watch cliphist store

exec_always $scripts/gtk.sh
