name: Check deps

on: [push]

jobs:
  checks:
    name: Check install script
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Checkout
      run: |
        pacman -Sy && pacman -S git --noconfirm
        git clone https://github.com/obsqrbtz/archdots.git .dotfiles
        cd .dotfiles
        git submodule update --init --recursive
    - name: Run install script
      run: |
        useradd --shell=/bin/bash build
        usermod -L build
        mkdir /home/build
        chown build:build /home/build
        echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        su build
        chmod +x .dotfiles/scripts/install_deps.sh
        .dotfiles/scripts/install_deps.sh
        rm .gitconfig
        stow -R -v -t ~ .
